In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [5]:
df = pd.read_csv("IRIS.csv")

In [7]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
df = df.drop("Id", axis=1)

In [11]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [49]:
x = df.drop("Species", axis=1)
y = df["Species"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.5, random_state = 42
)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

knn_model = KNeighborsClassifier(n_neighbors = 9)
knn_model.fit(x_train_scaled, y_train)

y_pred = knn_model.predict(x_test_scaled)

print("accuracy_score:", accuracy_score(y_test, y_pred) * 100, "%")
print("precision_score:", precision_score(y_test, y_pred, average='weighted') * 100, "%")
print("recall_score:", recall_score(y_test, y_pred, average='weighted') * 100, "%")

accuracy_score: 98.66666666666667 %
precision_score: 98.72222222222223 %
recall_score: 98.66666666666667 %

In [20]:
from sklearn.model_selection import GridSearchCV

classifier = KNeighborsClassifier()
grid = {"n_neighbors":[3,5,7,9]}
classifierCV = GridSearchCV(
    classifier,
    grid,
    cv = 5
)

classifierCV.fit(x_train_scaled, y_train)

y_pred = classifierCV.predict(x_test_scaled)

print("accuracy_score:", accuracy_score(y_test, y_pred) * 100, "%")
print("precision_score:", precision_score(y_test, y_pred, average='weighted') * 100, "%")
print("recall_score:", recall_score(y_test, y_pred, average='weighted') * 100, "%")

accuracy_score: 96.0 %
precision_score: 96.46153846153845 %
recall_score: 96.0 %

In [36]:
import pandas as pd

# result
res = pd.DataFrame(classifierCV.cv_results_)
print(res[["param_n_neighbors","mean_score_time"]])

  param_n_neighbors  mean_score_time
0                 3         0.001200
1                 5         0.001360
2                 7         0.005646
3                 9         0.007017